// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ_qZ9VbTZ9KI58MhiaJMfOt-dTaoZ1pM',
    appId: '1:920326297363:web:89135cc4bb4b1349c36ce6',
    messagingSenderId: '920326297363',
    projectId: 'my-refuge-acec0',
    authDomain: 'my-refuge-acec0.firebaseapp.com',
    storageBucket: 'my-refuge-acec0.firebasestorage.app',
    measurementId: 'G-E5ZWRZ8PPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg7olTBm13kM6p6HssCkWV3euwVCBN8CE',
    appId: '1:920326297363:android:a89cf4863302ef4bc36ce6',
    messagingSenderId: '920326297363',
    projectId: 'my-refuge-acec0',
    storageBucket: 'my-refuge-acec0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK7GBvTeykFYR8CL5Qwl4DcLUjeCrzgio',
    appId: '1:920326297363:ios:178c6c4e794cccb9c36ce6',
    messagingSenderId: '920326297363',
    projectId: 'my-refuge-acec0',
    storageBucket: 'my-refuge-acec0.firebasestorage.app',
    iosBundleId: 'com.example.myRefuge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK7GBvTeykFYR8CL5Qwl4DcLUjeCrzgio',
    appId: '1:920326297363:ios:178c6c4e794cccb9c36ce6',
    messagingSenderId: '920326297363',
    projectId: 'my-refuge-acec0',
    storageBucket: 'my-refuge-acec0.firebasestorage.app',
    iosBundleId: 'com.example.myRefuge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ_qZ9VbTZ9KI58MhiaJMfOt-dTaoZ1pM',
    appId: '1:920326297363:web:b750d9d67933e28dc36ce6',
    messagingSenderId: '920326297363',
    projectId: 'my-refuge-acec0',
    authDomain: 'my-refuge-acec0.firebaseapp.com',
    storageBucket: 'my-refuge-acec0.firebasestorage.app',
    measurementId: 'G-8DXC4YNJCC',
  );

}