// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEu2xyDsRHntwl-84Th0ywN5O-P8MzP7E',
    appId: '1:897560463762:web:1fc2928d4d45d9f1f5d94b',
    messagingSenderId: '897560463762',
    projectId: 'aula-298d6',
    authDomain: 'aula-298d6.firebaseapp.com',
    storageBucket: 'aula-298d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbxq7ceEyvEiugigj7KFqpDyidjGfQfv8',
    appId: '1:897560463762:android:0e46a5b7c3b5df81f5d94b',
    messagingSenderId: '897560463762',
    projectId: 'aula-298d6',
    storageBucket: 'aula-298d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkgHHh-z4bBbRkGM5vAoVJtu8YEy8lTpI',
    appId: '1:897560463762:ios:83383eae6cc36f23f5d94b',
    messagingSenderId: '897560463762',
    projectId: 'aula-298d6',
    storageBucket: 'aula-298d6.firebasestorage.app',
    iosBundleId: 'com.example.myRefuge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkgHHh-z4bBbRkGM5vAoVJtu8YEy8lTpI',
    appId: '1:897560463762:ios:83383eae6cc36f23f5d94b',
    messagingSenderId: '897560463762',
    projectId: 'aula-298d6',
    storageBucket: 'aula-298d6.firebasestorage.app',
    iosBundleId: 'com.example.myRefuge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEu2xyDsRHntwl-84Th0ywN5O-P8MzP7E',
    appId: '1:897560463762:web:2f955256aaeba659f5d94b',
    messagingSenderId: '897560463762',
    projectId: 'aula-298d6',
    authDomain: 'aula-298d6.firebaseapp.com',
    storageBucket: 'aula-298d6.firebasestorage.app',
  );
}
